name: .NET Build
# This action is currently very basic, and it does not yet build a usuable packaged app

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore app dependencies
      run: dotnet restore

    - name: Build app
      run: dotnet build
